rails_homeworks/config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get 'signup', to: 'users#new',        as: 'signup'
  get 'login',  to: 'sessions#new',     as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :sessions, :users, :petitions, :votes
end

rails_homeworks/app/models/petition.rb
class Petition < ActiveRecord::Base
  belongs_to :user

  has_many :votes

  def already_voted? u
    votes.where(user_id: u.id).any?
  end
end

rails_homeworks/app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :petitions
  has_many :votes

  validates :email, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true

  def name
    "#{first_name} #{last_name}"
  end
end

rails_homeworks/app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :petition

  validates :user_id, uniqueness: { scope:  :petition_id }
end

rails_homeworks/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
    def current_user
      if session[:user_id]
        @current_user ||= User.find(session[:user_id])
      end
    end

    helper_method :current_user

    def authorize
      if current_user.nil?
        redirect_to login_url, alert: 'Нет авторизации'
      end
    end
end

rails_homeworks/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @petitions = Petition.order(created_at: :desc).limit(10)
  end
end

rails_homeworks/app/controllers/petitions_controller.rb
class PetitionsController < ApplicationController
  before_action :authorize, only: [:new, :create]

  def index
    @petitions = Petition.all
    if params[:my]
      @petitions = @petitions.where(user: current_user)
      render 'my_petitions'
    end
  end

  def new
    @petition = current_user.petitions.new
  end

  def create
    petition = current_user.petitions.create(permitted_params)
    redirect_to petition
  end

  def show
    @petition = Petition.find(params[:id])
  end

  def edit
    @petition = current_user.petitions.find(params[:id])
  end

  def update # POST /petitions/:id
    petition = current_user.petitions.find(params[:id])
    petition.update(permitted_params)
    redirect_to petition, notice: "Петиция обновлена"
  end

  def destroy
    petition = current_user.petitions.find(params[:id])
    petition.destroy
    redirect_to petitions_path, notice: "Петиция удалена"
  end

  private

  def permitted_params
    params.require(:petition).permit(:id, :title, :body)
  end
end

rails_homeworks/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Здравствуйте!"
    else
      flash.now.alert = "Вы ввели неправильные пароль или email"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "До свидания!"
  end
end

rails_homeworks/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(permitted_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: 'Добро пожаловать!'
    else
      render 'new'
    end
  end

  private

  def permitted_params
    params.require(:user).permit(:email, :first_name, :last_name, :password, :password_confirmation)
  end
end

rails_homeworks/app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def create
    vote = current_user.votes.create(permitted_params)
    redirect_to vote.petition
  end

  before_filter :authorize

  private

    def permitted_params
      params.permit(:petition_id)
    end
end

rails_homeworks/app/helpers/application_helper.rb
module ApplicationHelper
end

rails_homeworks/app/helpers/home_helper.rb
module HomeHelper
end

rails_homeworks/app/helpers/petitions_helper.rb
module PetitionsHelper
end

rails_homeworks/app/helpers/sessions_helper.rb
module SessionsHelper
end

rails_homeworks/app/helpers/users_helper.rb
module UsersHelper
end

rails_homeworks/app/helpers/votes_helper.rb
module VotesHelper
end

rails_homeworks/app/views/home/index.html.erb
<h2>Последние 10 петиций</h2>

<table class="table">
  <thead>
    <tr>
      <th>Петиция</th>
      <th>Автор</th>
      <th>Голоса</th>
      <th>Дата создания</th>
    </tr>
  </thead>

  <% @petitions.each do |petition| %>
    <%= render 'petitions/petition', petition: petition %>
  <% end %>
</table>

rails_homeworks/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Петиции нашего района</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div align="right">
    <h6>
      <% if current_user %>
        <%= current_user.first_name %>
        <%= current_user.last_name %>
        (<%= current_user.email %>) |
        <%= link_to "Выйти", logout_path %>
      <% else %>
        <%= link_to "Зарегистрироваться", signup_path %> |
        <%= link_to "Войти", login_path %>
      <% end %>
    </h6>
  </div>

  <div align="right">
    <h6>
      <%= link_to "Все петиции", petitions_path %> |
      <%= link_to "Создать петицию", new_petition_path %>
      <% if current_user %>
        |
        <%= link_to "Мои петиции", petitions_path(my: true) %>
      <% end %>
    </h6>
  </div>

  <div align="left">
    <%= link_to "Онлайн петиции нашего района", root_path %>
    <%#<a class="navbar-brand" href="/">Онлайн петиции нашего района</a>%>
  </div>

  <%= bootstrap_flash %>
  <%= yield %>

  <footer>
    <p>&copy; rails_homeworks software incorporated 2016</p>
  </footer>

</body>
</html>

rails_homeworks/app/views/petitions/_form_common.html.erb
<%= form_for @petition do |f| %>
  <% if @petition.errors.any? %>
    <div class="error_explanation">
      <h2>Form is invalid</h2>
      <ul>
        <% @petition.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, 'Название' %><br>
    <%= f.text_field :title %>
  </div>
  <div class="form-group">
    <%= f.label :body, 'Описание' %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <% if @petition.new_record? %>
      <%= submit_tag 'Cоздать', class: "btn btn-primary" %>
    <% else %>
      <%= submit_tag 'Изменить', class: "btn btn-warning" %>
    <% end %>
  </div>
<% end %>

rails_homeworks/app/views/petitions/_petition.html.erb
    <tr>
      <td><%= link_to petition.title, petition_path(petition) %></td>
      <td><%= petition.user.name %></td>
      <td><center><%= petition.votes.count %></center></td>
      <td><%= petition.created_at.strftime '%d/%m/%Y %H:%M' %>
    </tr>

rails_homeworks/app/views/petitions/edit.html.erb
<h2>Изминение петиции</h2>

<%= render 'form_common' %>

rails_homeworks/app/views/petitions/index.html.erb
<h2><%= params[:my] ? "Мои" : "Все" %> петиции</h2>

<table class="table">
  <thead>
    <tr>
      <th>Петиции</th>
      <th>Автор</th>
      <th>Голоса</th>
      <th>Дата создания</th>
    </tr>
  </thead>

  <% @petitions.each do |petition| %>
    <%= render 'petitions/petition', petition: petition %>
  <% end %>
</table>

rails_homeworks/app/views/petitions/my_petitions.html.erb
<h2>Мои петиции</h2>

<table class="table">
  <thead>
  <tr>
    <th>Петиция</th>
    <th>Голоса</th>
    <th>Дата создания</th>
    <th colspan="2"><center>Действия</center></th>
  </tr>
  </thead>

  <% @petitions.each do |petition| %>
    <tr>
      <td><%= link_to petition.title, petition_path(petition) %></td>
      <td><center><%= petition.votes.count %></center></td>
      <td><%= petition.created_at.strftime('%d/%m/%Y %H:%M') %></td>
      <td><%= link_to 'Изменить', edit_petition_path(petition) %></td>
      <td><%= link_to 'Удалить', petition, method: :delete %></td>
    </tr>
  <% end %>
</table>

rails_homeworks/app/views/petitions/new.html.erb
<h2>Новая петиция</h2>

<%= render 'form_common' %>

rails_homeworks/app/views/petitions/show.html.erb
<h2>Петиция</h2>
<h4><%= @petition.title %></h4>
<tt><%= @petition.created_at.strftime '%d/%m/%Y %H:%M' %></tt>

<p>
  <%= @petition.body %>
</p>

<p>
Голосов: <%= @petition.votes.count %>
</p>

<p>
  <% if current_user %>
    <% if @petition.already_voted?(current_user) %>
      Вы уже поддержали данную петицию
    <% else %>
      <%= button_to "Поддержать", votes_path(petition_id: @petition.id) %>
    <% end %>
  <% else %>
    <i>Авторизуйтесь, для того, что-бы иметь возможность поддержать эту петицию</i>
  <% end %>
</p>

rails_homeworks/app/views/users/new.html.erb
<h1>Регистрация</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.label :first_name, 'Имя'%><br />
    <%= f.text_field :first_name %>
  </div>
  <div>
    <%= f.label :last_name, "Фамилия" %><br />
    <%= f.text_field :last_name %>
  </div>
  <div>
    <%= f.label :password, 'Пароль' %><br />
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation, 'Подтверждение пароля' %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div><%= f.submit "Зарегистрироваться" %></div>
<% end %>